# Generated by Django 5.1 on 2024-10-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='game.tournament'),
        ),
        migrations.AddField(
            model_name='play',
            name='tournament_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
