# Generated by Django 5.1 on 2024-10-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_play_tournament_play_tournament_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
